name: 04-github_secrets
## Triggers the workflow on when there is a push, or
## pull request on the main branch

on:
  # Allow run it manually
  [workflow_dispatch]

jobs:
  job1:
    ## The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        ## Reference your environment variables
        run: echo "The API key is:${{secrets.API_KEY}}"

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step 1
        ## Reference your environment variables
        run: echo "The API key is:${{secrets.API_KEY}}"
