name: 24-use_output_from_called_workflow

on:
  workflow_dispatch:

jobs:
  job1:
    # local repo
    # uses: ./.github/workflows/called-workflow.yml@v1
    # other repo
    # owner/repository/.github/workflows/called-workflow.yml@v1
    uses: ./.github/workflows/23-can_be_call_&_pass_data.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
