name: 26-to_call_another_repo_workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      workflow2_name:
        description: "Workflow to call Name for Triggering"
        required: true
        default: "dispatch_workflow"

      workflow2_github_account:
        description: "GitHub Account Owner"
        required: true
        default: "github-actions"

      workflow2_repo_github:
        description: "GitHub Repository Name"
        required: true
        default: "test-github-env"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  use_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: {}
    env:
      # pat_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      payload_Baseline_Number: "ABC_123"
      payload_Baseline_Revision: "main:front-2.0.32:34efe2"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        name: octocat
        run: |
          gh api /octocat

      - env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        name: octocat_second
        run: |
          gh api --header 'Accept: application/vnd.github+json' --header 'X-GitHub-Api-Version:2022-11-28' --method GET /octocat

      - env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        name: list_problem
        run: |
          gh api --header 'Accept: application/vnd.github+json' --method GET /repos/octocat/Spoon-Knife/issues

      - env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        name: get_with_parameters
        run: |
          gh api --header 'Accept: application/vnd.github+json' --method GET /repos/octocat/Spoon-Knife/issues -F per_page=2 -f sort=updated -f direction=asc

      - env:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        name: post_with_body
        run: |
          gh api --header 'Accept: application/vnd.github+json' --method POST /repos/octocat/Spoon-Knife/issues -f title="Created with the REST API" -f body="This is a test issue created by the REST API"

  #     - env:
  #         GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
  #       name: trigger_repository_workflow
  #       run: |
  #         gh api --header 'Accept: application/vnd.github+json' --method POST /repos/${{ github.event.inputs.workflow2_github_account}}/${{ github.event.inputs.workflow2_repo_github}}/dispatches -f title="Created with the REST API" -f body="This is a test issue created by the REST API"

  #         gh api /repos/${{ github.event.inputs.workflow2_github_account}}/${{ github.event.inputs.workflow2_repo_github}}/actions/workflows/build_dev.yml/dispatches \
  #  --input - <<< '{"ref":"master","inputs":{"BuildTarget":"all"}}'

  # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  # - uses: actions/checkout@v3

  # - name: setup python
  #   uses: actions/setup-python@v2
  #   with:
  #    python-version: 3.8 #install the python needed

  # - name: Install dependencies
  #   run: |
  #      cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
  #      python -m pip install --upgrade pip
  #      pip install -r requirements.txt

  # - name: Trigger the Workflow
  #   run: |
  #    cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
  #    python $GITHUB_WORKSPACE/Deployment-Scripts/workflow_trigger.py ${{ env.pat_token }}
  # ${{ github.event.inputs.workflow2_github_account}}
  #  ${{ github.event.inputs.workflow2_repo_github}}

  #   ${{ github.event.inputs.workflow2_name}}
  #    ${{ env.payload_Baseline_Number }}
  #     ${{ env.payload_Baseline_Revision }}
