name: 26-to_call_another_repo_workflow

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      workflow2_name:
        description: "Workflow to call Name for Triggering"
        required: true
        default: "dispatch_workflow"

      workflow2_github_account:
        description: "GitHub Account Owner"
        required: true
        default: "github-actions"

      workflow2_repo_github:
        description: "GitHub Repository Name"
        required: true
        default: "Horsty80/test-github-env"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"

  use_api:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions: {}
    env:
      # pat_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
      payload_Baseline_Number: "ABC_123"
      payload_Baseline_Revision: "main:front-2.0.32:34efe2"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - octocat:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: |
          gh api /octocat

      - octocat_second:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: |
          gh api --header 'Accept: application/vnd.github+json' --header 'X-GitHub-Api-Version:2022-11-28' --method GET /octocat

      - list_problem:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: |
          gh api --header 'Accept: application/vnd.github+json' --method GET /repos/octocat/Spoon-Knife/issues

      - with_parameters:
          GH_TOKEN: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
        run: |
          gh api --header 'Accept: application/vnd.github+json' --method GET /repos/octocat/Spoon-Knife/issues -F per_page=2 -f sort=updated -f direction=asc

      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3

      # - name: setup python
      #   uses: actions/setup-python@v2
      #   with:
      #    python-version: 3.8 #install the python needed

      # - name: Install dependencies
      #   run: |
      #      cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
      #      python -m pip install --upgrade pip
      #      pip install -r requirements.txt

      # - name: Trigger the Workflow
      #   run: |
      #    cd "$GITHUB_WORKSPACE/Deployment-Scripts/"
      #    python $GITHUB_WORKSPACE/Deployment-Scripts/workflow_trigger.py ${{ env.pat_token }}  ${{ github.event.inputs.workflow2_github_account}}  ${{ github.event.inputs.workflow2_repo_github}} ${{ github.event.inputs.workflow2_name}} ${{ env.payload_Baseline_Number }} ${{ env.payload_Baseline_Revision }}
